name-template: 'v$RESOLVED_VERSION.0'
tag-template: 'v$RESOLVED_VERSION.0'
tag-prefix: 'v'
categories:
  - title: 'Fixed'
    labels:
      - '📊 insights'
      - '🐛 bug'
      - '🌳 dependencies'
  - title: 'Added'
    labels:
      - '✨ enhancement'
      - '💡 ideas'
  - title: 'Changed'
    labels:
      - '🚀 major'
      - '⚠️ invalid'
  - title: 'Security'
    label: '🔒 security'
exclude-labels:
  - '🙈 skip-changelog'
  - '📝 documentation'
  - '📞 help wanted'
  - '🤔 question'
  - '😶 wontfix'
version-resolver:
  major:
    labels:
      - '🚀 major'
  minor:
    labels:
      - '✨ enhancement'
      - '💡 ideas'
  patch:
    labels:
      - '📊 insights'
      - '🐛 bug'
      - '🌳 dependencies'
      - '⚠️ invalid'
      - '🔒 security'
  default: patch
autolabeler:
  - label: '🙈 skip-changelog'
    files:
      - '*.json'
  - label: '📝 documentation'
    files:
      - '*.md'
category-template: '### $TITLE'
change-template: '- $TITLE ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&'
template: |
  $CHANGES
  ### Deprecated

  -
  ### Removed

  -
