name: Merge PTE to AppSource

on:
  push:
    branches:
      - 'release/PTE'

permissions:
  contents: write

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge PTE -> AppSource
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: release/AppSource
          github_token: ${{ secrets.GITHUB_TOKEN }}
